### ISSUE TITLE
Broken links in documentation pages

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_documentation#13]
1. For the pages of controlled terms on readthedocs , the link to library instances appears to be broken.

Example page: https://openminds-documentation.readthedocs.io/en/latest/schema_specifications/controlledTerms/biologicalSex.html

Broken Link: https://openminds-documentation.readthedocs.io/en/latest/libraries/terminologies/biologicalSex.html

2. Also, for the Instance page there is a link back to the schema page, but the link is unformatted
https://openminds-documentation.readthedocs.io/en/latest/instance_libraries/terminologies/biologicalSex.html

**Comment by lzehl** [comment]
@ehennestad thanks for reporting this. this is fixed now. (still need to update the code for the case there is no instance library as e.g. for the older versions. but the errors in latest is fixed)
