### ISSUE TITLE
BACK TO TOP link in instance library pages does not work

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_documentation#18]
- For **terminology** pages the link points the the schema page for the respective instances.
- For **contentTypes** the link is broken
- For **licenses** the link is broken

**Comment by lzehl** [comment]
@ehennestad 

**terminology issue** not sure what you meant but I think it's fixed.  

**contentTypes issue** not sure which link you are referring to but I think it's fixed. 

**licenses issue** not sure which link you are referring to but I think it's fixed. 

Can you double check and close the issue if everything is solved (or provide more detailed information on what is broken)?

**Comment by ehennestad** [comment]
Everything works as it should now!
