### ISSUE TITLE
Feedback on Getting started: versions of writing

### ISSUE THREAD

**Issue by aeidi89** [openMetadataInitiative/openMINDS_documentation#2]
In the 'Getting started' pages, the use of v1, v2 and v3 for versions of writing is confusing as this is also used for the different version for openMINDS. 

@apdavison suggest:
“compact-with-vocab”, “compact” and “expanded” for v1, v2, v3

@olinux suggest:
https://www.w3.org/TR/json-ld11-api/#expansion
would mean; "compacted", "expanded" and "with IRI"

For context, some examples:
v1
```
{
  "@context": {
    "@vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "_:zaphod-beeblebrox",
  "@type": "https://openminds.ebrains.eu/core/Person",
  "givenName": "Zaphod"
}
```

v2
```
{
  "@context": {
    "vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "_:zaphod-beeblebrox",
  "@type": "https://openminds.ebrains.eu/core/Person",
  "vocab:givenName": "Zaphod"
}
```

v3
```
{
  "@id": "_:zaphod-beeblebrox",
  "@type": "https://openminds.ebrains.eu/core/Person",
  "https://openminds.ebrains.eu/vocab/givenName": "Zaphod"
}
```

**Comment by lzehl** [comment]
solved with https://github.com/openMetadataInitiative/openMINDS_documentation/commit/ec05a581fea3964a10eafbd59cceb0b0718f98ed
