### ISSUE TITLE
Potential misspelling

### ISSUE THREAD

**Issue by aeidi89** [openMetadataInitiative/openMINDS_documentation#9]
Is "Instanciation" misspelled in this [Getting started page](https://openminds-documentation.readthedocs.io/en/latest/shared/getting_started.html)?

https://en.wiktionary.org/wiki/instantiation#English

I would prefer that 'instantiation' was replaced with 'creation of a metadata instance', or that 'instantiation' was explained.

Here is the definition from the [instantiation entry in Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/instantiation):
"something that [represents](https://dictionary.cambridge.org/dictionary/english/represent) or is an [example](https://dictionary.cambridge.org/dictionary/english/example) of something [else](https://dictionary.cambridge.org/dictionary/english/else), or the [act](https://dictionary.cambridge.org/dictionary/english/act) of [producing](https://dictionary.cambridge.org/dictionary/english/produce) something like this"

This is the [instantiate entry in Merriam-Webster](https://www.merriam-webster.com/dictionary/instantiate): 
"to represent (an abstraction) by a concrete [instance](https://www.merriam-webster.com/dictionary/instance)"

**Comment by lzehl** [comment]
@aeidi89 there was a big update in the meantime for this page. I think all your issues were solved / disappeared in that update.
